const navItems=document.querySelectorAll('.nav-item'),pages=document.querySelectorAll('.page'),title=document.getElementById('pageTitle'),sidebar=document.getElementById('sidebar');

const VERSUS_KEY='unbeerable_versus_duel_v1';
const VERSUS_WEEKS=4;
function defaultVersus(){const names=["HECT","edeN","FML","IMI","WYZ","MKT","AdHD","8EER","pc6","UPt","xBoM","DxL","7IB","B52","tMp","KTI"];return{teams:names.map(name=>({name,power:'',nationality:''})),results:{}}}
function loadVersus(){try{const x=JSON.parse(localStorage.getItem(VERSUS_KEY)||'null');if(x&&x.teams?.length===16)return x}catch{}return defaultVersus()}
let versusData=loadVersus();
(function migrateVersusPlaceholders(){
  const names=['HECT','edeN','FML','IMI','WYZ','MKT','AdHD','8EER','pc6','UPt','xBoM','DxL','7IB','B52','tMp','KTI'];
  const untouched=versusData.teams?.length===16&&versusData.teams.every((t,i)=>t.name==='Alliance '+(i+1))&&Object.keys(versusData.results||{}).length===0;
  if(untouched){
    versusData.teams=names.map((name,i)=>({name,power:versusData.teams[i]?.power||'',nationality:versusData.teams[i]?.nationality||''}));
    localStorage.setItem(VERSUS_KEY,JSON.stringify(versusData));
  }
})();
let versusSaveTimer=null,versusCloudLoaded=false;
function saveVersus(){localStorage.setItem(VERSUS_KEY,JSON.stringify(versusData));if(cloudReady&&versusCloudLoaded){clearTimeout(versusSaveTimer);versusSaveTimer=setTimeout(saveVersusCloud,350)}}
async function saveVersusCloud(showStatus=false){const status=document.getElementById('versusSaveStatus');if(!cloudReady){if(showStatus&&status)status.textContent='Cloud not connected';return false}try{if(showStatus&&status)status.textContent='Saving…';await api('/rest/v1/versus_active_tournament?on_conflict=slot',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({slot:'current',tournament_data:versusData,updated_at:new Date().toISOString()})});if(status)status.textContent='Saved to cloud';return true}catch(e){console.warn('Versus autosave failed',e);if(status)status.textContent='Save failed';if(showStatus)alert('Could not save Versus data: '+e.message);return false}}
async function loadActiveVersus(){if(!cloudReady)return;try{const rows=await api('/rest/v1/versus_active_tournament?slot=eq.current&select=tournament_data,updated_at');if(rows?.length&&rows[0].tournament_data?.teams?.length===16){versusData=rows[0].tournament_data;localStorage.setItem(VERSUS_KEY,JSON.stringify(versusData));renderVersus()}else{await api('/rest/v1/versus_active_tournament',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({slot:'current',tournament_data:versusData})})}versusCloudLoaded=true}catch(e){console.warn('Versus active load failed',e);versusCloudLoaded=true}}
function resultFor(teamIndex,week){for(const [key,r] of Object.entries(versusData.results)){const [w,m]=key.split('-').map(Number);if(w!==week)continue;const p=versusPairings(week)[m];if(!p)continue;if(p.a===teamIndex)return r;if(p.b===teamIndex)return r==='W'?'L':r==='L'?'W':''}return''}
function pathBefore(teamIndex,week){let p='';for(let w=1;w<week;w++)p+=resultFor(teamIndex,w);return p}
function fullPath(teamIndex){let p='';for(let w=1;w<=VERSUS_WEEKS;w++){const r=resultFor(teamIndex,w);if(!r)break;p+=r}return p}
function pathStrength(path){let n=0;for(const c of path)n=n*2+(c==='W'?1:0);return n}
function versusPairings(week){
 if(week===1)return Array.from({length:8},(_,i)=>({a:i*2,b:i*2+1,path:''}));
 const groups={};for(let i=0;i<16;i++){const p=pathBefore(i,week);if(p.length!==week-1)continue;(groups[p]??=[]).push(i)}
 return Object.keys(groups).sort((a,b)=>pathStrength(b)-pathStrength(a)||a.localeCompare(b)).flatMap(path=>{
   const g=groups[path],out=[];for(let i=0;i+1<g.length;i+=2)out.push({a:g[i],b:g[i+1],path});return out
 })
}
function versusRecord(i){const p=fullPath(i);return{w:[...p].filter(x=>x==='W').length,l:[...p].filter(x=>x==='L').length,path:p}}
function renderDashboardVersus(){
 const el=document.getElementById('dashboardVersusOpponent'),badge=document.getElementById('dashboardVersusWeek');if(!el||!badge)return;
 const idx=versusData.teams.findIndex(t=>(t.name||'').trim().toUpperCase()==='8EER');
 if(idx<0){badge.textContent='Week —';el.innerHTML='<div class="train-empty">8EER is not in the active Versus tournament.</div>';return}
 let week=1;
 for(let w=1;w<=VERSUS_WEEKS;w++){if(!resultFor(idx,w)){week=w;break}week=Math.min(w+1,VERSUS_WEEKS)}
 const pair=versusPairings(week).find(p=>p.a===idx||p.b===idx);
 badge.textContent='Week '+week;
 if(!pair){el.innerHTML='<div class="train-empty">Complete the previous week to generate 8EER’s next opponent.</div>';return}
 const oi=pair.a===idx?pair.b:pair.a,me=versusData.teams[idx],opp=versusData.teams[oi],rec=versusRecord(idx),orec=versusRecord(oi),done=!!resultFor(idx,week);
 el.innerHTML='<div class="versus-dashboard-match"><div class="versus-dashboard-team home"><small>YOUR ALLIANCE</small><strong>8EER</strong><span>'+esc(me.power||'Power —')+'</span><div class="versus-dashboard-record">'+rec.w+'-'+rec.l+' <b>'+esc(rec.path||'Opening')+'</b></div></div><div class="versus-dashboard-vs"><span>VS</span><small>'+(done?'Week complete':'Current matchup')+'</small></div><div class="versus-dashboard-team"><small>OPPONENT</small><strong>'+esc(opp.name||('Alliance '+(oi+1)))+'</strong><span>'+esc(opp.power||'Power —')+'</span><div class="versus-dashboard-record">'+orec.w+'-'+orec.l+' <b>'+esc(orec.path||'Opening')+'</b></div><em>'+esc(opp.nationality||'Region —')+'</em></div></div>'
}
function renderVersus(){
 const list=document.getElementById('versusTeamList'),weeks=document.getElementById('versusWeeks'),stand=document.getElementById('versusStandingsBody');if(!list||!weeks||!stand)return;
 list.innerHTML=versusData.teams.map((t,i)=>'<div class="versus-team-row"><span class="versus-seed">#'+(i+1)+'</span><input data-vteam="'+i+'" data-field="name" value="'+esc(t.name)+'" placeholder="Alliance name"><input data-vteam="'+i+'" data-field="power" value="'+esc(t.power)+'" placeholder="Power"><select data-vteam="'+i+'" data-field="nationality"><option value="">Nationality</option>'+['Europe','America','Asia','Middle East'].map(n=>'<option value="'+n+'" '+(t.nationality===n?'selected':'')+'>'+n+'</option>').join('')+'</select></div>').join('');
 list.querySelectorAll('input,select').forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.vteam),field=inp.dataset.field;versusData.teams[i][field]=inp.value.trim();saveVersus();renderVersus()});
 weeks.innerHTML=Array.from({length:4},(_,wi)=>{const week=wi+1,pairs=versusPairings(week);return '<article class="panel versus-week"><div class="panel-head"><div><span class="eyebrow">WEEK '+week+'</span><h3>'+(week===1?'Opening Pairings':'Path Pairings')+'</h3></div><span class="pill">'+(week===1?'Original order':'Exact '+('W/L '.repeat(week-1)).trim()+' path')+'</span></div><div class="versus-matches">'+(pairs.length?pairs.map((p,mi)=>versusMatchHtml(week,mi,p)).join(''):'<p class="muted">Complete Week '+(week-1)+' results to generate these pairings.</p>')+'</div></article>'}).join('');
 document.querySelectorAll('.versus-result').forEach(sel=>sel.onchange=()=>{const key=sel.dataset.key;if(sel.value)versusData.results[key]=sel.value;else delete versusData.results[key];for(const k of Object.keys(versusData.results)){const w=Number(k.split('-')[0]);if(w>Number(key.split('-')[0]))delete versusData.results[k]}saveVersus();renderVersus()});
 const rows=versusData.teams.map((t,i)=>({i,t,...versusRecord(i)})).sort((a,b)=>b.w-a.w||a.i-b.i);
 renderDashboardVersus();
 stand.innerHTML=rows.map((r,rank)=>'<tr><td>'+(rank+1)+'</td><td><strong>'+esc(r.t.name)+'</strong></td><td>'+esc(r.t.power||'—')+'</td><td>'+r.w+'</td><td>'+r.l+'</td><td>'+r.w+'-'+r.l+'</td><td><span class="path-badge">'+esc(r.path||'—')+'</span></td></tr>').join('')
}
function versusMatchHtml(week,mi,p){const a=versusData.teams[p.a],b=versusData.teams[p.b],key=week+'-'+mi,r=versusData.results[key]||'',br=r==='W'?'L':r==='L'?'W':'',winner=r?(r==='W'?a.name:b.name):'—',loser=r?(r==='W'?b.name:a.name):'—';return '<div class="versus-match"><div class="versus-match-head"><strong>Match '+(mi+1)+'</strong><span class="path-badge">'+(p.path||'START')+'</span></div><div class="versus-side"><span>A</span><strong>'+esc(a.name)+'</strong><small>'+esc(a.power||'Power —')+'</small><select class="versus-result" data-key="'+key+'"><option value="">Result</option><option value="W" '+(r==='W'?'selected':'')+'>W</option><option value="L" '+(r==='L'?'selected':'')+'>L</option></select></div><div class="versus-side"><span>B</span><strong>'+esc(b.name)+'</strong><small>'+esc(b.power||'Power —')+'</small><b class="auto-result">'+(br||'—')+'</b></div><div class="versus-outcome"><span>Winner: <strong>'+esc(winner)+'</strong></span><span>Loser: <strong>'+esc(loser)+'</strong></span></div></div>'}

function parseVersusOcr(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),rows=[];for(const line of lines){if(rows.length>=16)break;let clean=line.replace(/^\s*#?\d{1,2}[.)\-:]?\s+/,'').trim();if(!clean)continue;const m=clean.match(/^(.*?)(?:\s{2,}|\s+)([\d,.]+\s*[KMBT]?)$/i);if(m)rows.push({name:m[1].trim(),power:m[2].trim()});else rows.push({name:clean,power:''})}return rows}
async function scanVersusPicture(file){const review=document.getElementById('versusPictureReview'),preview=document.getElementById('versusPicturePreview'),status=document.getElementById('versusOcrStatus'),box=document.getElementById('versusOcrText');if(!file||!review||!box)return;review.hidden=false;const reader=new FileReader();reader.onload=()=>preview.src=reader.result;reader.readAsDataURL(file);if(!window.Tesseract){status.textContent='Picture reader did not load. Refresh and try again.';return}status.textContent='Reading picture… 0%';box.value='';try{const result=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')status.textContent='Reading picture… '+Math.round((m.progress||0)*100)+'%'}});box.value=result.data.text.trim();status.textContent='Scan complete. Review the text, then select Apply detected teams.'}catch(e){status.textContent='Could not read this picture: '+e.message}}
function applyVersusOcr(){const box=document.getElementById('versusOcrText'),status=document.getElementById('versusOcrStatus'),rows=parseVersusOcr(box?.value||'');if(!rows.length){if(status)status.textContent='No alliance rows detected. Edit the text and try again.';return}rows.slice(0,16).forEach((r,i)=>{versusData.teams[i]={name:r.name||versusData.teams[i].name,power:r.power||'',nationality:versusData.teams[i].nationality||''}});saveVersus();renderVersus();document.getElementById('versusPictureReview').hidden=true}
function cancelVersusOcr(){document.getElementById('versusPictureReview').hidden=true;document.getElementById('versusPictureInput').value=''}


let versusHistory=[];
function versusComplete(){return Object.keys(versusData.results).filter(k=>versusData.results[k]==='W'||versusData.results[k]==='L').length===32}
function versusSnapshot(){return{version:1,teams:versusData.teams.map((t,i)=>({...t,original_order:i+1,record:versusRecord(i),weeks:Array.from({length:4},(_,wi)=>{const week=wi+1,pair=versusPairings(week).find(p=>p.a===i||p.b===i),opp=pair?(pair.a===i?pair.b:pair.a):null;return{week,opponent:opp===null?null:versusData.teams[opp].name,result:resultFor(i,week)}})})),results:{...versusData.results}}}
async function loadVersusHistory(){if(!cloudReady)return;try{versusHistory=await api('/rest/v1/versus_tournament_history?select=id,completed_at,tournament_data&order=completed_at.desc');renderVersusHistory()}catch(e){console.warn('Versus history load failed',e)}}
function renderVersusHistory(){const root=document.getElementById('versusHistory'),count=document.getElementById('versusHistoryCount');if(!root)return;if(count)count.textContent=versusHistory.length+' archived';root.innerHTML=versusHistory.length?versusHistory.map((h,hi)=>{const teams=h.tournament_data?.teams||[],date=new Date(h.completed_at).toLocaleDateString();return '<details class="versus-history-item"><summary><strong>Tournament '+(versusHistory.length-hi)+'</strong><span>'+esc(date)+' · '+teams.length+' alliances</span></summary><div class="monthly-rotation"><table class="rotation-table"><thead><tr><th>#</th><th>Alliance</th><th>Power</th><th>Nationality</th><th>Record</th><th>Path</th></tr></thead><tbody>'+teams.slice().sort((a,b)=>(b.record?.w||0)-(a.record?.w||0)||(a.original_order||0)-(b.original_order||0)).map(t=>'<tr><td>'+esc(t.original_order)+'</td><td><strong>'+esc(t.name)+'</strong></td><td>'+esc(t.power||'—')+'</td><td>'+esc(t.nationality||'—')+'</td><td>'+esc((t.record?.w||0)+'-'+(t.record?.l||0))+'</td><td><span class="path-badge">'+esc(t.record?.path||'—')+'</span></td></tr>').join('')+'</tbody></table></div></details>'}).join(''):'<p class="muted">No completed tournaments archived yet.</p>'}
async function archiveVersus(){if(!versusComplete())return alert('Complete all 32 matches across Weeks 1–4 before archiving this tournament.');if(!cloudReady)return alert('Connect to the shared cloud before archiving.');if(!confirm('Are you sure you want to archive this tournament? The full 4-week results will be saved to Tournament History.'))return;try{await api('/rest/v1/versus_tournament_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({tournament_data:versusSnapshot()})});await loadVersusHistory();alert('Tournament archived. You can now reset the tournament to start the next one.')}catch(e){alert('Could not archive tournament: '+e.message)}}

async function undoLatestVersusArchive(){if(!cloudReady)return alert('Connect to the shared cloud first.');if(!versusHistory.length)return alert('There is no archived tournament to undo.');const latest=versusHistory[0];if(!confirm('Are you sure you want to undo the latest archive? This will permanently remove that tournament from Tournament History.'))return;try{await api('/rest/v1/versus_tournament_history?id=eq.'+encodeURIComponent(latest.id),{method:'DELETE',headers:{Prefer:'return=minimal'}});await loadVersusHistory();alert('Latest tournament archive removed.')}catch(e){alert('Could not undo latest archive: '+e.message)}}
function resetVersus(){if(!confirm('Reset all Versus Duel teams, power values, and results?'))return;versusData=defaultVersus();saveVersus();renderVersus()}

const titles={dashboard:'Alliance Dashboard','season-war':'Season War',members:'Members','todays-schedule':'Today’s Schedule',vs:'Versus Duel','desert-storm':'Desert Storm','canyon-storm':'Canyon Storm',transfer:'Transfer Planning',train:'Train',settings:'Settings'};
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));navItems.forEach(n=>n.classList.toggle('active',n.dataset.page===id));title.textContent=titles[id]||id;sidebar.classList.remove('open')}
navItems.forEach(n=>n.onclick=()=>showPage(n.dataset.page));document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
const STORAGE_KEY='unbeerable_members_v14';let members=loadMembers(),editingIndex=null,importRows=[],workbook=null;
function memberObj(x){return typeof x==='string'?{name:x,power:'',t1:'',type:''}:{name:String(x?.name||''),power:String(x?.power||''),t1:String(x?.t1||''),type:String(x?.type||'')}}
function loadMembers(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('unbeerable_members_v13')||'[]');return Array.isArray(x)?x.filter(Boolean).map(memberObj):[]}catch(e){return[]}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(members))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parseTHP(v){const raw=String(v??'').trim();if(!raw)return 0;const s=raw.replace(/[\s,]/g,'').replace(/[^0-9.+-]/g,''),n=Number(s);if(!Number.isFinite(n))return 0;return n<1000000?n*1000000:n}
function compactTHP(n){if(n>=1e9)return (n/1e9).toFixed(n>=1e10?1:2).replace(/\.0+$|(?<=\.[0-9])0$/,'')+'B';if(n>=1e6)return (n/1e6).toFixed(n>=1e8?1:2).replace(/\.0+$|(?<=\.[0-9])0$/,'')+'M';if(n>=1e3)return (n/1e3).toFixed(1).replace(/\.0$/,'')+'K';return Math.round(n).toLocaleString()}
function updateCount(){const n=members.length,total=members.reduce((sum,m)=>sum+parseTHP(m.power),0);document.getElementById('dashboardMemberCount').textContent=n+'/100';document.getElementById('dashboardMemberSlots').textContent=Math.max(0,100-n)+' open position'+(100-n===1?'':'s');const p=document.getElementById('dashboardTotalPower'),s=document.getElementById('dashboardTotalPowerSource');if(p)p.textContent=compactTHP(total);if(s)s.textContent=total?'Combined member THP':'No THP data'}
function renderMembers(){members=members.map(memberObj).filter(m=>m.name);const q=(document.getElementById('memberSearch').value||'').trim().toLowerCase();const rows=members.map((member,index)=>({member,index})).filter(x=>[x.member.name,x.member.power,x.member.t1,x.member.type].some(v=>String(v).toLowerCase().includes(q)));document.querySelector('#memberTable tbody').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.member.name)}</strong></td><td>${esc(x.member.power||'—')}</td><td>${esc(x.member.t1||'—')}</td><td>${esc(x.member.type||'—')}</td><td class="row-actions"><button class="mini-btn edit-member" data-index="${x.index}">Edit</button><button class="mini-btn danger delete-member" data-index="${x.index}">Delete</button></td></tr>`).join('');document.getElementById('memberCount').textContent=members.length+' member'+(members.length===1?'':'s');document.getElementById('visibleMemberCount').textContent=rows.length+' shown';document.getElementById('memberEmptyState').hidden=rows.length!==0;updateCount();document.querySelectorAll('.edit-member').forEach(b=>b.onclick=()=>openMember(Number(b.dataset.index)));document.querySelectorAll('.delete-member').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.index);if(confirm('Delete '+members[i].name+' from the roster?')){members.splice(i,1);saveLocal();renderMembers();await replaceCloudRoster()}})}
function openMember(i=null){editingIndex=i;document.getElementById('memberModalTitle').textContent=i===null?'Add member':'Edit member';const m=i===null?memberObj({}):members[i];document.getElementById('memberNameInput').value=m.name;document.getElementById('memberPowerInput').value=m.power;document.getElementById('memberT1Input').value=m.t1;document.getElementById('memberTypeInput').value=m.type;document.getElementById('memberModal').hidden=false}
function closeMember(){document.getElementById('memberModal').hidden=true;editingIndex=null}
document.getElementById('addMemberBtn').onclick=()=>openMember();document.getElementById('closeMemberModal').onclick=closeMember;document.getElementById('cancelMemberBtn').onclick=closeMember;
document.getElementById('saveMemberBtn').onclick=async()=>{const m={name:document.getElementById('memberNameInput').value.trim(),power:document.getElementById('memberPowerInput').value.trim(),t1:document.getElementById('memberT1Input').value.trim(),type:document.getElementById('memberTypeInput').value.trim()};if(!m.name)return alert('Enter a member name.');if(members.some((n,i)=>i!==editingIndex&&n.name.toLowerCase()===m.name.toLowerCase()))return alert('That member is already in the roster.');if(editingIndex===null)members.push(m);else members[editingIndex]=m;saveLocal();renderMembers();closeMember();await replaceCloudRoster()};
document.getElementById('memberSearch').oninput=renderMembers;document.getElementById('clearMemberSearch').onclick=()=>{document.getElementById('memberSearch').value='';renderMembers()};
function parseCSV(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);return rows}
const HEADERS=['alliance member','member name','member','player name','player','name','username'];function norm(v){return String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ')}
function prepareImport(rows,file){let h=null;for(let r=0;r<Math.min(rows.length,20)&&!h;r++){const z=rows[r].map(norm),i=z.findIndex(c=>HEADERS.includes(c));if(i>=0)h={r,name:i,power:z.findIndex(c=>c==='thp'||c==='power'),t1:z.findIndex(c=>c==='t1'),type:z.findIndex(c=>c==='type')}}if(!h)return alert('Could not find a member-name column.');const map=new Map();for(const r of rows.slice(h.r+1)){const name=String(r[h.name]??'').trim();if(!name)continue;map.set(name.toLowerCase(),{name,power:h.power>=0?String(r[h.power]??'').trim():'',t1:h.t1>=0?String(r[h.t1]??'').trim():'',type:h.type>=0?String(r[h.type]??'').trim():''})}importRows=[...map.values()];if(!importRows.length)return alert('No members found.');document.getElementById('importSummary').textContent=importRows.length+' members found in '+file+'. THP, T1 and Type will be imported when present.';document.getElementById('importPreview').innerHTML=importRows.map((m,i)=>`<div><span>${i+1}</span><strong>${esc(m.name)}</strong><small>${esc(m.power||'—')} · T1 ${esc(m.t1||'—')} · ${esc(m.type||'—')}</small></div>`).join('');document.getElementById('importModal').hidden=false}
const fileInput=document.getElementById('memberFileInput');document.getElementById('importMembersBtn').onclick=()=>fileInput.click();fileInput.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const buf=await f.arrayBuffer(),u=new Uint8Array(buf);if(u[0]===0x50&&u[1]===0x4b||u[0]===0xd0&&u[1]===0xcf){if(typeof XLSX==='undefined')throw Error('Excel reader unavailable');workbook=XLSX.read(buf,{type:'array'});let s=workbook.SheetNames[0],sheetRows=null;for(const sn of workbook.SheetNames){const rr=XLSX.utils.sheet_to_json(workbook.Sheets[sn],{header:1,defval:'',raw:false});if(rr.slice(0,20).some(row=>row.map(norm).some(c=>HEADERS.includes(c)))){s=sn;sheetRows=rr;break}}prepareImport(sheetRows||XLSX.utils.sheet_to_json(workbook.Sheets[s],{header:1,defval:'',raw:false}),f.name)}else prepareImport(parseCSV(new TextDecoder().decode(buf)),f.name)}catch(err){alert('Could not read file: '+err.message)}e.target.value=''};
function closeImport(){document.getElementById('importModal').hidden=true;importRows=[]}document.getElementById('closeImportModal').onclick=closeImport;document.getElementById('cancelImportBtn').onclick=closeImport;document.getElementById('replaceRosterBtn').onclick=async()=>{if(!importRows.length)return;if(confirm('Replace roster with '+importRows.length+' imported names?')){members=importRows.map(memberObj);saveLocal();renderMembers();closeImport();await replaceCloudRoster()}};
const URL='https://dznwbouaslgmdzfjglcm.supabase.co',KEY='sb_publishable_VXk1Hspaj07VMf8N5-QIfQ_SBfta9IB';let cloudReady=false,accessToken=localStorage.getItem('unbeerable_access_token')||'';
function cloudUI(ok,msg){cloudReady=ok;document.getElementById('cloudStatus').innerHTML='<span></span> '+(ok?'Shared cloud':'Local data');document.getElementById('cloudSettingsStatus').textContent=ok?'Connected':'Not connected';document.getElementById('cloudMessage').textContent=msg;document.getElementById('pullCloudBtn').disabled=!ok}
async function api(path,options={}){const headers={apikey:KEY,'Content-Type':'application/json',...(accessToken?{Authorization:'Bearer '+accessToken}:{}),...(options.headers||{})};const r=await fetch(URL+path,{...options,headers});if(!r.ok){let m='HTTP '+r.status;try{const j=await r.json();m=j.message||j.msg||j.error_description||j.error||m}catch{}throw Error(m)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function ensureAuth(){if(accessToken){try{await api('/auth/v1/user');return true}catch{accessToken='';localStorage.removeItem('unbeerable_access_token')}}const data=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({data:{},gotrue_meta_security:{}})});accessToken=data?.access_token||data?.session?.access_token||'';if(!accessToken)throw Error('Anonymous sign-in did not return a session. Enable Anonymous Sign-Ins in Supabase.');localStorage.setItem('unbeerable_access_token',accessToken);return true}
async function readCloud(){return await api('/rest/v1/alliance_members?select=name,power,t1,type&order=created_at.asc')}
function signedCompact(n){const x=Number(n)||0;return (x>0?'+':x<0?'−':'')+compactTHP(Math.abs(x))}
function growthClass(n){return Number(n)>0?'up':Number(n)<0?'down':'flat'}
async function loadRosterGrowth(){
 const powerEl=document.getElementById('dashboardPowerChange'),memberEl=document.getElementById('dashboardMemberChange'),trend=document.getElementById('dashboardGrowthTrend');
 if(!trend)return;
 try{
  const data=await api('/rest/v1/roster_growth_history?select=recorded_at,source_modified_at,member_count,total_thp&order=recorded_at.asc&limit=90');
  if(!data?.length)return;
  const first=data[0],last=data[data.length-1],prev=data.length>1?data[data.length-2]:null;
  const powerDelta=prev?Number(last.total_thp)-Number(prev.total_thp):0,memberDelta=prev?last.member_count-prev.member_count:0;
  const totalPowerDelta=Number(last.total_thp)-Number(first.total_thp),totalMemberDelta=last.member_count-first.member_count;
  if(powerEl){powerEl.className='metric-change '+growthClass(powerDelta);powerEl.textContent=prev?signedCompact(powerDelta)+' vs previous sync':'Baseline captured'}
  if(memberEl){memberEl.className='metric-change '+growthClass(memberDelta);memberEl.textContent=prev?(memberDelta>0?'+':'')+memberDelta+' vs previous sync':'Baseline captured'}
  const gp=document.getElementById('growthPowerDelta'),gm=document.getElementById('growthMemberDelta'),gc=document.getElementById('growthSnapshotCount'),period=document.getElementById('growthPeriod');
  if(gp){gp.className=growthClass(totalPowerDelta);gp.textContent=data.length>1?signedCompact(totalPowerDelta):'—'}
  if(gm){gm.className=growthClass(totalMemberDelta);gm.textContent=data.length>1?(totalMemberDelta>0?'+':'')+totalMemberDelta:'—'}
  if(gc)gc.textContent=data.length;
  if(period)period.textContent=data.length>1?new Date(first.recorded_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})+' → '+new Date(last.recorded_at).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Baseline '+new Date(last.recorded_at).toLocaleDateString(undefined,{month:'short',day:'numeric'});
  if(data.length<2){trend.innerHTML='<div class="train-empty">Baseline captured at '+compactTHP(Number(last.total_thp))+' THP and '+last.member_count+' members. Growth will appear after the next changed Drive roster sync.</div>';return}
  const vals=data.map(x=>Number(x.total_thp)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,w=800,h=150,pad=14;
  const pts=data.map((x,i)=>{const px=pad+(i/(data.length-1))*(w-pad*2),py=h-pad-((Number(x.total_thp)-min)/span)*(h-pad*2);return px.toFixed(1)+','+py.toFixed(1)}).join(' ');
  trend.innerHTML='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Total Power growth trend"><polyline points="'+pts+'" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="growth-axis"><span>'+new Date(first.recorded_at).toLocaleDateString()+' · '+compactTHP(Number(first.total_thp))+'</span><span>'+new Date(last.recorded_at).toLocaleDateString()+' · '+compactTHP(Number(last.total_thp))+'</span></div>';
 }catch(e){console.warn('Roster growth load failed',e);trend.innerHTML='<div class="train-empty">Growth history is temporarily unavailable.</div>'}
}
async function loadRosterSyncStatus(){
 const root=document.getElementById('rosterSyncStatus'),pill=document.getElementById('rosterSyncPill'),state=document.getElementById('rosterSyncState'),rows=document.getElementById('rosterSyncRows'),time=document.getElementById('rosterSyncTime'),source=document.getElementById('rosterSyncSource'),error=document.getElementById('rosterSyncError');
 if(!root)return;
 try{
   const data=await api('/rest/v1/roster_sync_status?source_key=eq.alliance_members_drive&select=source_name,last_synced_at,row_count,status,error_message&limit=1');
   const x=data?.[0];
   if(!x){pill.textContent='No sync yet';state.textContent='Waiting';rows.textContent='—';time.textContent='—';root.classList.remove('sync-ok','sync-error');return}
   const ok=x.status==='ok';
   root.classList.toggle('sync-ok',ok);root.classList.toggle('sync-error',!ok);
   pill.textContent=ok?'Synced':'Sync error';state.textContent=ok?'OK':'Error';rows.textContent=Number.isFinite(Number(x.row_count))?Number(x.row_count).toLocaleString():'—';
   time.textContent=x.last_synced_at?new Date(x.last_synced_at).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
   source.textContent=x.source_name||'Alliance members Data / alliance_members.xlsm';
   if(error){error.hidden=!x.error_message;error.textContent=x.error_message||''}
 }catch(e){
   root.classList.remove('sync-ok');root.classList.add('sync-error');pill.textContent='Unavailable';state.textContent='Could not read status';if(error){error.hidden=false;error.textContent=e.message}
 }
}
async function pullCloudRoster(){try{const data=await readCloud();members=(data||[]).filter(x=>x.name).map(memberObj);saveLocal();renderMembers();cloudUI(true,'Synced '+members.length+' shared member'+(members.length===1?'':'s')+'.');renderTrain()}catch(e){cloudUI(false,'Cloud read failed: '+e.message)}}
async function replaceCloudRoster(){if(!cloudReady)return;try{await api('/rest/v1/alliance_members?id=not.is.null',{method:'DELETE',headers:{Prefer:'return=minimal'}});if(members.length)await api('/rest/v1/alliance_members',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(members.map(m=>({name:m.name,power:m.power||null,t1:m.t1||null,type:m.type||null})))});cloudUI(true,'Saved '+members.length+' members to shared roster.')}catch(e){cloudUI(false,'Cloud write failed: '+e.message)}}
async function initCloud(){try{await ensureAuth();const data=await readCloud();if((data||[]).length===0&&members.length){cloudReady=true;await replaceCloudRoster();await loadRosterSyncStatus();await loadVersusHistory();await loadActiveVersus()}else{members=(data||[]).filter(x=>x.name).map(memberObj);saveLocal();renderMembers();cloudUI(true,'Connected to shared roster.');loadRosterSyncStatus();loadRosterGrowth();loadTrainData();loadVersusHistory();loadActiveVersus()}setInterval(()=>{if(cloudReady){pullCloudRoster();loadRosterSyncStatus();loadRosterGrowth()}},15000)}catch(e){cloudUI(false,'Cloud connection failed: '+e.message)}}

const TRAIN_CONDUCTORS=["Xerilaz","CobraCai67","TurdFerguson III","RealbloodlineOTC","Draks","Chimaniac","NathyP","PvD1981","La Fleche","Aniton","Droopy Jr","Tampaxxx","Spogre","Ziffy","Devilnight1","Marechal440","Biggie4o1","Hawk","EneLdo2","Dr Daniel Jackson","Farm and Furious","Bocu","JonazxFather","Suncloud","Miltfeli","Kielbach","Manu","Lulubutt","Brothers","Fulöl","Romilius Lupercal","Adnan","LuffyDM","Maria CL","Aramil310","Elpatron","Dr Dev","Adrï","Jord4nn92","Kitty Twopointzero","Hidata","Bilbo Baggins","Jiomer","Fab","Knekke","Poseidon","Peumieufaire","Banjol","Gecko","Kännikala","Erries","Nikos","Merakkels","Agressorxx","Miss PMF","Jonto","Shumat","07Shorne","Wojtello","Hocine19","Diziria","nice cup of tea","Bad Blower","Gulitch","Vlad","HuskyVic","Wolfzh","Hungrymile","Lordael","Petitdrop","Robert N","Peacax","Seebueb","mshar","Floormaster","HerrBBQmaster","Relx","Astro","Zebulon","Destroyer","Eierkopp1337","GeeX","Bhellzy","Im Batman","fra984","Donka","Reez0r","LassoLasse","totenkrieger","Whales","PEKA","The great broly","Gentleman Driver","Tank Rebel","AlexAZ","Rocktailer","Pandi Crush","Hisoka","Collector","Hardone"];
const TRAIN_VIPS=["Hidata","Bilbo Baggins","Jiomer","Fab","Knekke","Poseidon","Peumieufaire","Banjol","Gecko","Kännikala","Erries","Nikos","Merakkels","Agressorxx","Miss PMF","Jonto","Shumat","07Shorne","Wojtello","Hocine19","Diziria","nice cup of tea","Gulitch","Vlad","HuskyVic","Wolfzh","Hungrymile","Lordael","Petitdrop","Robert N","Peacax","Seebueb","mshar","Floormaster","HerrBBQmaster","Relx","Astro","Zebulon","Xerilaz","CobraCai67","TurdFerguson III","RealbloodlineOTC","Draks","Chimaniac","NathyP","PvD1981","La Fleche","Aniton","Droopy Jr","Tampaxxx","Spogre","Ziffy","Devilnight1","Marechal440","Biggie4o1","Hawk","EneLdo2","Dr Daniel Jackson","Farm and Furious","Bocu","JonazxFather","Suncloud","Miltfeli","Kielbach","Manu","Lulubutt","Brothers","Fulöl","Romilius Lupercal","Adnan","LuffyDM","Maria CL","Aramil310","Elpatron","Dr Dev","Adrï","Jord4nn92","Kitty Twopointzero","Hisoka","Pandi Crush","Rocktailer","AlexAZ","Tank Rebel","Gentleman Driver","The great broly","PEKA","Whales","totenkrieger","LassoLasse","Reez0r","Donka","fra984","Im Batman","Bhellzy","GeeX","Eierkopp1337","Destroyer","Bad Blower","Hardone","Collector"];
let trainTab='conductor',trainState={conductor:{next_index:0,cycle:1},vip:{next_index:0,cycle:1}},trainHistory=[];
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
function allianceNow(){const n=new Date();return new Date(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate(),12)}
function mondayOf(offset=0){const d=allianceNow(),day=d.getDay()||7;d.setDate(d.getDate()-day+1+offset*7);return d}
function isoDate(d){return d.toISOString().slice(0,10)}
function currentWeekStart(){return isoDate(mondayOf(0))}
function comingWeekStart(){return isoDate(mondayOf(1))}
function fallbackCurrentTrainRows(){const week=currentWeekStart(),start=68;return DAYS.flatMap((day,i)=>[{week_start:week,day_index:i,role:'conductor',member_name:TRAIN_CONDUCTORS[start+i],cycle:1,fallback:true},{week_start:week,day_index:i,role:'vip',member_name:TRAIN_VIPS[start+i],cycle:1,fallback:true}])}
function currentTrainRows(){const week=currentWeekStart(),saved=trainHistory.filter(x=>x.week_start===week);return saved.length?saved:fallbackCurrentTrainRows()}
function eligibleQueue(role){const source=role==='conductor'?TRAIN_CONDUCTORS:TRAIN_VIPS,set=new Set(members.map(x=>x.name.toLocaleLowerCase()));return source.filter(n=>set.has(n.toLocaleLowerCase()))}
function formatWeek(s){if(!s)return '—';const d=new Date(s+'T12:00:00'),e=new Date(d);e.setDate(e.getDate()+6);return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})+' – '+e.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
async function loadTrainData(){if(!cloudReady)return;try{const [st,hi]=await Promise.all([api('/rest/v1/train_rotation_state?select=role,next_index,cycle'),api('/rest/v1/train_rotation_history?select=week_start,day_index,role,member_name,cycle&order=week_start.desc,day_index.asc')]);(st||[]).forEach(x=>trainState[x.role]={next_index:x.next_index,cycle:x.cycle});trainHistory=hi||[];renderTrain()}catch(e){console.warn('Train load failed',e)}}
function trainEmailMessage(){const week=comingWeekStart(),rows=trainHistory.filter(x=>x.week_start===week);if(!rows.length)return '';const lines=DAYS.map((day,i)=>{const c=rows.find(x=>x.day_index===i&&x.role==='conductor'),v=rows.find(x=>x.day_index===i&&x.role==='vip');return day+' — Driver: '+(c?.member_name||'—')+' | VIP: '+(v?.member_name||'—')});return '# Train rotation for next week\n\nDear all,\n\nThank you for your participation this week 🏆\n\nNext week’s train drivers and vips are assigned according to the list (which can be found on discord). 🚂✨\n\n📅 Train rotation:\n'+lines.join('\n')+'\n\nGeneral instructions:\n⏰ The train starts daily around 17:00 CEST.\n🚂 Drivers have 4h to turn the train golden & choose the VIP.\n⭐ VIPs have 1h to accept after nomination.\n🎁 Please include at least one deco chest / deco components in the train.\n✉️ If your day/time doesn’t work or if you have questions, contact me.\n⚠️ Drivers & VIPs are responsible for being available on their assigned day, so please check your schedule carefully.\n\n🔥 The train drivers and vips will be assigned according to the list (which can be found on discord).\n\nHave a great week! 🌟🍻'}
function renderTrainEmail(){const box=document.getElementById('trainEmailText'),btn=document.getElementById('copyTrainEmailBtn');if(!box)return;const msg=trainEmailMessage();box.value=msg;box.placeholder=msg?'':'Generate the coming week to create the email.';if(btn)btn.disabled=!msg}
async function copyTrainEmail(){const text=trainEmailMessage(),status=document.getElementById('trainCopyStatus');if(!text)return;try{await navigator.clipboard.writeText(text);if(status)status.textContent='Copied to clipboard.'}catch{const box=document.getElementById('trainEmailText');box.focus();box.select();document.execCommand('copy');if(status)status.textContent='Copied to clipboard.'}setTimeout(()=>{if(status)status.textContent=''},2500)}
function renderDashboardTrain(){const el=document.getElementById('dashboardTrainSchedule'),head=document.getElementById('dashboardTrainWeek');if(!el||!head)return;const week=currentWeekStart(),rows=currentTrainRows(),saved=trainHistory.some(x=>x.week_start===week);head.textContent='Current week · '+formatWeek(week)+(saved?'':' · temporary #69–75');el.innerHTML=DAYS.map((day,i)=>{const c=rows.find(x=>x.day_index===i&&x.role==='conductor'),v=rows.find(x=>x.day_index===i&&x.role==='vip');return '<div class="dashboard-train-day"><span>'+day+'</span><div><small>CONDUCTOR</small><strong>'+esc(c?.member_name||'—')+'</strong></div><div><small>VIP</small><strong>'+esc(v?.member_name||'—')+'</strong></div></div>'}).join('')}
function renderTrain(){renderDashboardTrain();renderTrainEmail();const role=trainTab,q=eligibleQueue(role),st=trainState[role]||{next_index:0,cycle:1},week=comingWeekStart(),current=trainHistory.filter(x=>x.week_start===week&&x.role===role);document.getElementById('trainWeekLabel').textContent=formatWeek(week);['conductor','vip'].forEach(r=>{const qq=eligibleQueue(r),ss=trainState[r]||{next_index:0,cycle:1};document.getElementById(r+'Progress').textContent=Math.min(ss.next_index,qq.length)+'/'+qq.length;document.getElementById(r+'Cycle').textContent='Cycle '+ss.cycle});document.getElementById('trainRoleTitle').textContent=(role==='vip'?'VIP':'Conductor')+' schedule';document.getElementById('trainQueueTitle').textContent=(role==='vip'?'VIP':'Conductor')+' list';document.getElementById('trainEligibleCount').textContent=q.length+' eligible';document.getElementById('trainSchedule').innerHTML=DAYS.map((day,i)=>{const x=current.find(v=>v.day_index===i);return '<div class="train-day"><span>'+day+'</span><strong>'+(x?esc(x.member_name):'Not generated')+'</strong><small>'+(x?'Cycle '+x.cycle:'')+'</small></div>'}).join('');document.getElementById('trainQueue').innerHTML=q.length?q.map((n,i)=>'<div class="train-person '+(i<st.next_index?'used ':'')+(i===st.next_index?'next':'')+'"><span class="num">'+(i+1)+'</span><strong>'+esc(n)+'</strong></div>').join(''):'<div class="train-empty">No names from this rotation list are currently in the alliance member roster.</div>';const weeks=[...new Set(trainHistory.map(x=>x.week_start))].sort().reverse();document.getElementById('trainHistory').innerHTML=weeks.length?weeks.map(w=>{const rows=trainHistory.filter(x=>x.week_start===w);return '<div class="train-history-week"><div class="train-history-head">'+formatWeek(w)+'</div><div class="train-history-grid">'+DAYS.map((d,i)=>{const cc=rows.find(x=>x.day_index===i&&x.role==='conductor'),vv=rows.find(x=>x.day_index===i&&x.role==='vip');return '<div class="train-history-cell"><span>'+d+'</span><div>C: '+esc(cc?.member_name||'—')+'</div><div>VIP: '+esc(vv?.member_name||'—')+'</div></div>'}).join('')+'</div></div>'}).join(''):'<div class="train-empty">No previous train rotations yet.</div>'}
async function generateRole(role,week,startNumber=null){const existing=trainHistory.filter(x=>x.week_start===week&&x.role===role);if(existing.length)return;const q=eligibleQueue(role);if(!q.length)throw Error('No eligible '+role+' members are in the alliance roster.');let st={...(trainState[role]||{next_index:0,cycle:1})},rows=[];if(startNumber!==null){if(!Number.isInteger(startNumber)||startNumber<1||startNumber>q.length)throw Error('Start # for '+role+' must be between 1 and '+q.length+'.');st.next_index=startNumber-1;}for(let day=0;day<7;day++){if(st.next_index>=q.length){st.next_index=0;st.cycle++}rows.push({week_start:week,day_index:day,role,member_name:q[st.next_index],cycle:st.cycle});st.next_index++}await api('/rest/v1/train_rotation_history',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)});await api('/rest/v1/train_rotation_state?role=eq.'+role,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({next_index:st.next_index,cycle:st.cycle,updated_at:new Date().toISOString()})})}
async function undoTrainWeek(){if(!cloudReady)return alert('Connect to the shared cloud first.');const week=comingWeekStart(),rows=trainHistory.filter(x=>x.week_start===week);if(!rows.length)return alert('There is no coming Train week to undo.');if(!confirm('Undo the coming week? This removes all 7 Conductor and 7 VIP assignments from history so you can generate it again.'))return;try{for(const role of ['conductor','vip']){const roleRows=rows.filter(x=>x.role===role).sort((a,b)=>a.day_index-b.day_index),q=eligibleQueue(role);if(roleRows.length){const first=roleRows[0],idx=q.findIndex(n=>n.toLocaleLowerCase()===first.member_name.toLocaleLowerCase());if(idx>=0){await api('/rest/v1/train_rotation_state?role=eq.'+role,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({next_index:idx,cycle:first.cycle,updated_at:new Date().toISOString()})})}}}await api('/rest/v1/train_rotation_history?week_start=eq.'+week,{method:'DELETE',headers:{Prefer:'return=minimal'}});document.getElementById('trainStartNumber').value='';await loadTrainData()}catch(e){alert('Could not undo Train week: '+e.message);await loadTrainData()}}
async function generateTrainWeek(){if(!cloudReady)return alert('Connect to the shared cloud first.');const week=comingWeekStart();if(trainHistory.some(x=>x.week_start===week))return alert('The coming week has already been generated.');const raw=document.getElementById('trainStartNumber').value.trim();const chosen=raw===''?null:Number(raw);try{await generateRole('conductor',week,chosen);await generateRole('vip',week,chosen);await loadTrainData()}catch(e){alert('Could not generate train week: '+e.message);await loadTrainData()}}
document.querySelectorAll('.train-tab').forEach(b=>b.onclick=()=>{trainTab=b.dataset.trainTab;document.querySelectorAll('.train-tab').forEach(x=>x.classList.toggle('active',x===b));renderTrain()});document.getElementById('generateTrainWeekBtn').onclick=generateTrainWeek;document.getElementById('copyTrainEmailBtn').onclick=copyTrainEmail;document.getElementById('undoTrainWeekBtn').onclick=undoTrainWeek;document.getElementById('trainRefreshBtn').onclick=loadTrainData;

document.getElementById('generateDailyEmailBtn').onclick=generateDailyEmail;document.getElementById('undoDailyEmailBtn').onclick=undoDailyEmail;document.getElementById('copyDailyEmailBtn').onclick=copyDailyEmail;
document.getElementById('versusPictureBtn').onclick=()=>document.getElementById('versusPictureInput').click();
document.getElementById('versusPictureInput').onchange=e=>scanVersusPicture(e.target.files[0]);
document.getElementById('versusApplyOcrBtn').onclick=applyVersusOcr;
document.getElementById('versusCancelOcrBtn').onclick=cancelVersusOcr;
document.getElementById('saveVersusBtn').onclick=()=>saveVersusCloud(true);
document.getElementById('archiveVersusBtn').onclick=archiveVersus;
document.getElementById('undoVersusArchiveBtn').onclick=undoLatestVersusArchive;
document.getElementById('resetVersusBtn').onclick=resetVersus;
document.getElementById('nextRotationBtn').onclick=nextRotationBlock;document.getElementById('undoRotationBtn').onclick=undoRotationBlock;
document.getElementById('vsStrategyToggle').onclick=()=>{const x=document.getElementById('vsStrategyOptions');x.hidden=!x.hidden};document.querySelectorAll('.vs-choice').forEach(b=>b.onclick=()=>{localStorage.setItem('unbeerable_vs_strategy',b.dataset.vsStrategy);renderReminders()});
document.getElementById('pullCloudBtn').onclick=pullCloudRoster;document.getElementById('resetRosterBtn').onclick=async()=>{if(confirm('Clear the shared member roster?')){members=[];saveLocal();renderMembers();await replaceCloudRoster()}};


const SHINY_SERVERS={"A":["678","683","684","685","690","691","697","698","699","707","708","715","722","723","724","725","726","732","733","738","739","740","741","742","748","749","750","756","765","766","767","768","773","774","775","776","784","785","793","794","801","802","803"],"B":["679","680","686","687","688","692","693","694","700","701","702","709","710","716","717","718","719","727","728","734","735","743","744","751","757","758","759","760","761","769","770","777","778","786","787","795","796","797","804"],"C":["677","681","682","689","695","696","703","704","705","706","711","712","713","714","720","721","729","730","731","736","737","745","746","747","752","753","754","755","762","763","764","771","772","779","780","781","782","783","788","789","790","791","792","798","799","800"]};
function shinyGroupForDate(d){const serial=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate(),12)-new Date(2026,6,1,12))/86400000),cycle=((serial%3)+3)%3;return cycle===0?'A':cycle===1?'B':'C'}
function emailEventLine(e){if(e.startsWith('🪖 Alliance Exercise'))return '* 21h CET / 17h ST : Alliance Exercise';if(e.startsWith('🧟 Zombie Siege'))return '* 20h CET / 16h ST : Zombie Siege';if(e.startsWith('🏜️ Canyon Storm'))return '* 16h CET / 12h ST : Canyon Storm';if(e.startsWith('🌪️ Desert Storm'))return '* 13h CET / 9h ST : Desert Storm Team A\n* 22h CET / 16h ST : Desert Storm Team B';return '* Free time'}
function dailyAllianceEmail(){const d=allianceNow(),events=rotationEventsForDate(d),day=d.getDay(),reminders=[];if([1,2,3].includes(day))reminders.push('* Register to DS');if([6,0,1,2].includes(day))reminders.push('* Register to Canyon Storm');const vs=localStorage.getItem('unbeerable_vs_strategy')||'';if(vs==='save')reminders.push('* Eco / Save week in VS');if(vs==='push')reminders.push('* Push week in VS');const group=shinyGroupForDate(d),servers=SHINY_SERVERS[group],shiny=servers?servers.map(x=>'#'+x).join(' '):'Group '+group+' secret-task servers';return '8EER,\n\nOn todays schedule we will have:\n\n'+events.map(emailEventLine).join('\n')+'\n\nREMINDER :\n\n'+(reminders.length?reminders.join('\n'):'* No active reminders')+'\n\nShiny secret tasks today :\n'+shiny+'\n\nIf you have any questions regarding the planning, please message me directly'}
let previousDailyEmail=null;
function generateDailyEmail(){const box=document.getElementById('dailyEmailText'),btn=document.getElementById('copyDailyEmailBtn'),undo=document.getElementById('undoDailyEmailBtn'),status=document.getElementById('dailyEmailStatus');if(!box)return;previousDailyEmail=box.value;box.value=dailyAllianceEmail();if(btn)btn.disabled=false;if(undo)undo.disabled=false;if(status)status.textContent='Generated from today’s live schedule. Undo is available.'}
function undoDailyEmail(){const box=document.getElementById('dailyEmailText'),undo=document.getElementById('undoDailyEmailBtn'),copy=document.getElementById('copyDailyEmailBtn'),status=document.getElementById('dailyEmailStatus');if(!box||previousDailyEmail===null)return;box.value=previousDailyEmail;previousDailyEmail=null;if(copy)copy.disabled=!box.value;if(undo)undo.disabled=true;if(status)status.textContent='Generation undone. Previous email restored.'}
async function copyDailyEmail(){const box=document.getElementById('dailyEmailText'),status=document.getElementById('dailyEmailStatus');if(!box?.value)return;try{await navigator.clipboard.writeText(box.value)}catch{box.focus();box.select();document.execCommand('copy')}if(status)status.textContent='Copied to clipboard.';setTimeout(()=>{if(status)status.textContent=''},2500)}
function renderShinyCalendar(){const root=document.getElementById('shinyCalendar');if(!root)return;const names=['July','August','September','October','November','December'],dow=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];root.innerHTML=names.map((name,mi)=>{const month=mi+6,first=new Date(2026,month,1),days=new Date(2026,month+1,0).getDate(),cells=[];dow.forEach(d=>cells.push('<span class="dow">'+d+'</span>'));for(let i=0;i<first.getDay();i++)cells.push('<span class="blank"></span>');for(let day=1;day<=days;day++){const d=new Date(2026,month,day),serial=Math.floor((d-new Date(2026,6,1))/86400000),cycle=((serial%3)+3)%3,group=cycle===0?'A':cycle===1?'B':'C',cls=cycle===0?'shiny-a':cycle===1?'shiny-b':'shiny-c';cells.push('<span class="day '+cls+'" data-shiny-date="'+d.getFullYear()+'-'+String(month+1).padStart(2,'0')+'-'+String(day).padStart(2,'0')+'" data-shiny-group="'+group+'" title="Group '+group+' · Cycle '+cycle+'">'+day+'</span>')}return '<div class="shiny-month"><h4>'+name+' 2026</h4><div class="shiny-grid">'+cells.join('')+'</div></div>'}).join('')}


const ROTATION_ANCHOR=new Date(2026,8,28,12);let rotationBlock=Math.max(0,Number(localStorage.getItem('unbeerable_rotation_block')||0));
function rotationEventsForDate(d){const serial=Math.round((new Date(d.getFullYear(),d.getMonth(),d.getDate(),12)-ROTATION_ANCHOR)/86400000),events=[];if((((serial-2)%3)+3)%3===0)events.push('🧟 Zombie Siege · 20h CET / 16h ST');if(((serial-1)%2+2)%2===0)events.push('🪖 Alliance Exercise · 21h CET / 17h ST');if(d.getDay()===4)events.push('🏜️ Canyon Storm · 16h CET / 12h ST');if(d.getDay()===5)events.push('🌪️ Desert Storm · Team A 13h CET / 9h ST · Team B 22h CET / 16h ST');return events.length?events:['🆓 Free time']}
function blockStart(block=rotationBlock){const d=new Date(ROTATION_ANCHOR);d.setDate(d.getDate()+block*28);return d}
function renderRotationCalendar(){const body=document.getElementById('rotationCalendarBody');if(!body)return;const start=blockStart(),days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],counts={marshal:0,zombie:0,canyon:0,desert:0,free:0};body.innerHTML=days.map((name,di)=>'<tr><th>'+name+'</th>'+[0,1,2,3].map(w=>{const d=new Date(start);d.setDate(d.getDate()+w*7+di);const ev=rotationEventsForDate(d);ev.forEach(e=>{if(e.includes('Alliance Exercise'))counts.marshal++;else if(e.includes('Zombie'))counts.zombie++;else if(e.includes('Canyon'))counts.canyon++;else if(e.includes('Desert'))counts.desert++;else if(e.includes('Free'))counts.free++});return '<td>'+ev.join('<br>')+'</td>'}).join('')+'</tr>').join('');document.getElementById('rotationTotals').innerHTML='<div><strong>'+counts.marshal+'</strong><span>🪖 Marshal</span></div><div><strong>'+counts.zombie+'</strong><span>🧟 Zombie Siege</span></div><div><strong>'+counts.canyon+'</strong><span>🏜️ Canyon Storm</span></div><div><strong>'+counts.desert+'</strong><span>🌪️ Desert Storm</span></div><div><strong>'+counts.free+'</strong><span>🆓 Free days</span></div>';const finish=new Date(start);finish.setDate(finish.getDate()+27);document.getElementById('rotationBlockLabel').textContent='Block '+(rotationBlock+1)+' · 4 weeks';const undo=document.getElementById('undoRotationBtn');if(undo)undo.disabled=rotationBlock<=0;document.getElementById('rotationRange').textContent=start.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})+' – '+finish.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function todayRotation(){const now=allianceNow(),today=new Date(now),days=Math.floor((today-ROTATION_ANCHOR)/86400000),week=((Math.floor(days/7)%4)+4)%4+1;return{now,week,events:rotationEventsForDate(today)}}
function renderDashboardToday(){const date=document.getElementById('dashboardTodayDate'),week=document.getElementById('dashboardRotationWeek'),events=document.getElementById('dashboardTodayEvents'),weekEl=document.getElementById('dashboardWeekEvents');if(!date||!week||!events)return;const x=todayRotation(),now=x.now,today=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12),dow=today.getDay()||7,monday=new Date(today);monday.setDate(today.getDate()-dow+1);date.textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});week.textContent='Week '+x.week+' of 4';events.innerHTML=x.events.map(e=>'<div class="today-event">'+e+'</div>').join('');if(weekEl)weekEl.innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const ev=rotationEventsForDate(d),isToday=d.toDateString()===today.toDateString();return '<div class="dashboard-week-day '+(isToday?'active':'')+'"><div class="dashboard-week-head"><strong>'+d.toLocaleDateString(undefined,{weekday:'short'})+'</strong><span>'+d.toLocaleDateString(undefined,{month:'short',day:'numeric'})+'</span></div><div class="dashboard-week-list">'+ev.map(e=>'<span>'+e+'</span>').join('')+'</div></div>'}).join('')}

function nextRotationBlock(){rotationBlock++;localStorage.setItem('unbeerable_rotation_block',rotationBlock);renderRotationCalendar()}
function undoRotationBlock(){if(rotationBlock<=0)return;rotationBlock--;localStorage.setItem('unbeerable_rotation_block',rotationBlock);renderRotationCalendar()}
function renderReminders(){const day=allianceNow().getDay(),names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],desert=[1,2,3].includes(day),canyon=[6,0,1,2].includes(day),d=document.getElementById('desertReminder'),c=document.getElementById('canyonReminder'),label=document.getElementById('reminderDay');if(label)label.textContent=names[day];if(d)d.classList.toggle('active',desert);if(c)c.classList.toggle('active',canyon);const saved=localStorage.getItem('unbeerable_vs_strategy')||'',status=document.getElementById('vsStrategyStatus');document.querySelectorAll('.vs-choice').forEach(b=>b.classList.toggle('active',b.dataset.vsStrategy===saved));if(status)status.textContent=saved==='push'?'Selected: Push in VS':saved==='save'?'Selected: Save in VS':'No VS strategy selected.'}
renderVersus();renderMembers();renderShinyCalendar();renderReminders();renderRotationCalendar();renderDashboardToday();setInterval(renderDashboardToday,60000);initCloud();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));