const navItems=document.querySelectorAll('.nav-item'),pages=document.querySelectorAll('.page'),title=document.getElementById('pageTitle'),sidebar=document.getElementById('sidebar');
const titles={dashboard:'Alliance Dashboard','season-war':'Season War',members:'Members',vs:'VS','desert-storm':'Desert Storm','canyon-storm':'Canyon Storm',transfer:'Transfer Planning',settings:'Settings'};
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));navItems.forEach(n=>n.classList.toggle('active',n.dataset.page===id));title.textContent=titles[id]||id;sidebar.classList.remove('open')}
navItems.forEach(n=>n.onclick=()=>showPage(n.dataset.page));document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
const STORAGE_KEY='unbeerable_members_v13';let members=loadMembers(),editingIndex=null,importRows=[],workbook=null;
function loadMembers(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(x)?x.filter(Boolean):[]}catch(e){return[]}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(members))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateCount(){const n=members.length;document.getElementById('dashboardMemberCount').textContent=n+'/100';document.getElementById('dashboardMemberSlots').textContent=Math.max(0,100-n)+' open position'+(100-n===1?'':'s')}
function renderMembers(){const q=(document.getElementById('memberSearch').value||'').trim().toLowerCase();const rows=members.map((name,index)=>({name,index})).filter(x=>x.name.toLowerCase().includes(q));document.querySelector('#memberTable tbody').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td class="row-actions"><button class="mini-btn edit-member" data-index="${x.index}">Edit</button><button class="mini-btn danger delete-member" data-index="${x.index}">Delete</button></td></tr>`).join('');document.getElementById('memberCount').textContent=members.length+' member'+(members.length===1?'':'s');document.getElementById('visibleMemberCount').textContent=rows.length+' shown';document.getElementById('memberEmptyState').hidden=rows.length!==0;updateCount();document.querySelectorAll('.edit-member').forEach(b=>b.onclick=()=>openMember(Number(b.dataset.index)));document.querySelectorAll('.delete-member').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.index);if(confirm('Delete '+members[i]+' from the roster?')){members.splice(i,1);saveLocal();renderMembers();await replaceCloudRoster()}})}
function openMember(i=null){editingIndex=i;document.getElementById('memberModalTitle').textContent=i===null?'Add member':'Edit member';document.getElementById('memberNameInput').value=i===null?'':members[i];document.getElementById('memberModal').hidden=false}
function closeMember(){document.getElementById('memberModal').hidden=true;editingIndex=null}
document.getElementById('addMemberBtn').onclick=()=>openMember();document.getElementById('closeMemberModal').onclick=closeMember;document.getElementById('cancelMemberBtn').onclick=closeMember;
document.getElementById('saveMemberBtn').onclick=async()=>{const name=document.getElementById('memberNameInput').value.trim();if(!name)return alert('Enter a member name.');if(members.some((n,i)=>i!==editingIndex&&n.toLowerCase()===name.toLowerCase()))return alert('That member is already in the roster.');if(editingIndex===null)members.push(name);else members[editingIndex]=name;saveLocal();renderMembers();closeMember();await replaceCloudRoster()};
document.getElementById('memberSearch').oninput=renderMembers;document.getElementById('clearMemberSearch').onclick=()=>{document.getElementById('memberSearch').value='';renderMembers()};
function parseCSV(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);return rows}
const HEADERS=['alliance member','member name','member','player name','player','name','username'];function norm(v){return String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ')}
function prepareImport(rows,file){let h=null;for(let r=0;r<Math.min(rows.length,20)&&!h;r++){const i=rows[r].map(norm).findIndex(c=>HEADERS.includes(c));if(i>=0)h={r,i}}if(!h)return alert('Could not find a member-name column.');importRows=[...new Map(rows.slice(h.r+1).map(r=>String(r[h.i]??'').trim()).filter(Boolean).map(n=>[n.toLowerCase(),n])).values()];if(!importRows.length)return alert('No member names found.');document.getElementById('importSummary').textContent=importRows.length+' member names found in '+file+'.';document.getElementById('importPreview').innerHTML=importRows.map((n,i)=>`<div><span>${i+1}</span><strong>${esc(n)}</strong></div>`).join('');document.getElementById('importModal').hidden=false}
const fileInput=document.getElementById('memberFileInput');document.getElementById('importMembersBtn').onclick=()=>fileInput.click();fileInput.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const buf=await f.arrayBuffer(),u=new Uint8Array(buf);if(u[0]===0x50&&u[1]===0x4b||u[0]===0xd0&&u[1]===0xcf){if(typeof XLSX==='undefined')throw Error('Excel reader unavailable');workbook=XLSX.read(buf,{type:'array'});const s=workbook.SheetNames[0];prepareImport(XLSX.utils.sheet_to_json(workbook.Sheets[s],{header:1,defval:''}),f.name)}else prepareImport(parseCSV(new TextDecoder().decode(buf)),f.name)}catch(err){alert('Could not read file: '+err.message)}e.target.value=''};
function closeImport(){document.getElementById('importModal').hidden=true;importRows=[]}document.getElementById('closeImportModal').onclick=closeImport;document.getElementById('cancelImportBtn').onclick=closeImport;document.getElementById('replaceRosterBtn').onclick=async()=>{if(!importRows.length)return;if(confirm('Replace roster with '+importRows.length+' imported names?')){members=[...importRows];saveLocal();renderMembers();closeImport();await replaceCloudRoster()}};
const URL='https://dznwbouaslgmdzfjglcm.supabase.co',KEY='sb_publishable_VXk1Hspaj07VMf8N5-QIfQ_SBfta9IB';let cloud=null,cloudReady=false,suppressRealtime=false;
function cloudUI(ok,msg){cloudReady=ok;document.getElementById('cloudStatus').innerHTML='<span></span> '+(ok?'Shared cloud':'Local data');document.getElementById('cloudSettingsStatus').textContent=ok?'Connected':'Not connected';document.getElementById('cloudMessage').textContent=msg;document.getElementById('pullCloudBtn').disabled=!ok}
async function pullCloudRoster(){if(!cloud)return;const {data,error}=await cloud.from('alliance_members').select('name').order('created_at');if(error)return cloudUI(false,'Cloud read failed: '+error.message);members=(data||[]).map(x=>x.name).filter(Boolean);saveLocal();renderMembers();cloudUI(true,'Synced '+members.length+' shared member'+(members.length===1?'':'s')+'.')}
async function replaceCloudRoster(){if(!cloudReady)return;suppressRealtime=true;try{const {error:d}=await cloud.from('alliance_members').delete().neq('id','00000000-0000-0000-0000-000000000000');if(d)throw d;if(members.length){const {error:i}=await cloud.from('alliance_members').insert(members.map(name=>({name})));if(i)throw i}cloudUI(true,'Saved '+members.length+' members to shared roster.')}catch(e){cloudUI(false,'Cloud write failed: '+e.message)}finally{setTimeout(()=>suppressRealtime=false,500)}}
async function initCloud(){if(!window.supabase)return cloudUI(false,'Supabase client did not load.');cloud=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await cloud.auth.getSession();if(!session){const {error}=await cloud.auth.signInAnonymously();if(error)return cloudUI(false,'Anonymous sign-in must be enabled in Supabase Authentication.')}const {data,error}=await cloud.from('alliance_members').select('name').order('created_at');if(error)return cloudUI(false,'Cloud connection failed: '+error.message);if((data||[]).length===0&&members.length){cloudReady=true;await replaceCloudRoster()}else{members=(data||[]).map(x=>x.name).filter(Boolean);saveLocal();renderMembers();cloudUI(true,'Connected to shared roster.')}cloud.channel('alliance-members-live').on('postgres_changes',{event:'*',schema:'public',table:'alliance_members'},()=>{if(!suppressRealtime)pullCloudRoster()}).subscribe()}
document.getElementById('pullCloudBtn').onclick=pullCloudRoster;document.getElementById('resetRosterBtn').onclick=async()=>{if(confirm('Clear the shared member roster?')){members=[];saveLocal();renderMembers();await replaceCloudRoster()}};
renderMembers();initCloud();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));